SET NAMES utf8mb4;
USE gamedb;

-- Fix map_config names
UPDATE map_config SET map_name = 'Làng Khởi Đầu' WHERE map_id = 0;
UPDATE map_config SET map_name = 'Địa cung (sơ cấp)' WHERE map_id = 6;
UPDATE map_config SET map_name = 'Địa cung (trung cấp)' WHERE map_id = 7;
UPDATE map_config SET map_name = 'Địa cung (cao cấp)' WHERE map_id = 18;
UPDATE map_config SET map_name = 'Địa cung (thượng cấp)' WHERE map_id = 19;
UPDATE map_config SET map_name = 'Đồi trung tâm' WHERE map_id = 56;
UPDATE map_config SET map_name = 'Thánh Địa Thất Kiếm' WHERE map_id = 57;
UPDATE map_config SET map_name = 'Hang Vô Thú' WHERE map_id = 58;
UPDATE map_config SET map_name = 'Làng Cát' WHERE map_id = 59;
UPDATE map_config SET map_name = 'Làng Sương Mù' WHERE map_id = 60;
UPDATE map_config SET map_name = 'Vách Chigiri' WHERE map_id = 61;
UPDATE map_config SET map_name = 'Núi Kirigakure' WHERE map_id = 62;
UPDATE map_config SET map_name = 'Cánh Đồng Kaminari' WHERE map_id = 63;
UPDATE map_config SET map_name = 'Thung Lũng Chết' WHERE map_id = 64;
UPDATE map_config SET map_name = 'Đồi Hoang' WHERE map_id = 65;
UPDATE map_config SET map_name = 'Hầm Núi Mizu' WHERE map_id = 66;
UPDATE map_config SET map_name = 'Hầm bí mật' WHERE map_id = 67;
UPDATE map_config SET map_name = 'Làng Cổ' WHERE map_id = 68;
UPDATE map_config SET map_name = 'Làng Mây' WHERE map_id = 69;
UPDATE map_config SET map_name = 'Vách Đá Ngang' WHERE map_id = 70;
UPDATE map_config SET map_name = 'Miếu Iwagakure' WHERE map_id = 71;
UPDATE map_config SET map_name = 'Chân Núi Tsuchi' WHERE map_id = 72;
UPDATE map_config SET map_name = 'Rừng Nấm' WHERE map_id = 73;
UPDATE map_config SET map_name = 'Dòng Sông Kusagakure' WHERE map_id = 74;
UPDATE map_config SET map_name = 'Làng Lá' WHERE map_id = 75;
UPDATE map_config SET map_name = 'Đồng Cỏ Tenchi' WHERE map_id = 76;
UPDATE map_config SET map_name = 'Rừng Kumogakure' WHERE map_id = 77;
UPDATE map_config SET map_name = 'Nghĩa Địa Bỏ Hoang' WHERE map_id = 78;
UPDATE map_config SET map_name = 'Chiến Trường Cổ' WHERE map_id = 79;
UPDATE map_config SET map_name = 'Đồi Cát' WHERE map_id = 80;
UPDATE map_config SET map_name = 'Sa mạc Sunagakure' WHERE map_id = 81;
UPDATE map_config SET map_name = 'Núi Hokage' WHERE map_id = 82;
UPDATE map_config SET map_name = 'Thung lũng Tấn Công' WHERE map_id = 83;
UPDATE map_config SET map_name = 'Khu luyện tập' WHERE map_id = 84;
UPDATE map_config SET map_name = 'Làng Đá' WHERE map_id = 85;
UPDATE map_config SET map_name = 'Trường Konoha' WHERE map_id = 86;
UPDATE map_config SET map_name = 'Hang Khổ' WHERE map_id = 87;
UPDATE map_config SET map_name = 'Cầu Kannabi' WHERE map_id = 88;
UPDATE map_config SET map_name = 'Vòng Lặp Ảo Tưởng' WHERE map_id = 89;
UPDATE map_config SET map_name = 'Hang Vô Thú (cấp 1)' WHERE map_id = 90;
UPDATE map_config SET map_name = 'Hang Vô Thú (cấp 2)' WHERE map_id = 91;
UPDATE map_config SET map_name = 'Hang Vô Thú (cấp 3)' WHERE map_id = 92;
UPDATE map_config SET map_name = 'Hang Gamaken' WHERE map_id = 93;
UPDATE map_config SET map_name = 'Hang Gamatatsu' WHERE map_id = 94;
UPDATE map_config SET map_name = 'Hang Gama Armored' WHERE map_id = 95;
UPDATE map_config SET map_name = 'Hang Gamabunta' WHERE map_id = 96;
UPDATE map_config SET map_name = 'Hang Gamahiro' WHERE map_id = 97;
UPDATE map_config SET map_name = 'Chiến trường' WHERE map_id = 98;
UPDATE map_config SET map_name = 'Cửa phía tây' WHERE map_id = 99;
UPDATE map_config SET map_name = 'Cửa phía đông' WHERE map_id = 100;
UPDATE map_config SET map_name = 'Chiến trường phó bản' WHERE map_id = 101;
UPDATE map_config SET map_name = 'Làng Mưa' WHERE map_id = 102;
UPDATE map_config SET map_name = 'Pháo Đài Amega' WHERE map_id = 103;
UPDATE map_config SET map_name = 'Vùng trũng Kusa' WHERE map_id = 104;
UPDATE map_config SET map_name = 'Lãnh Địa thiên thần' WHERE map_id = 105;
UPDATE map_config SET map_name = 'Căn cứ Akatsuki' WHERE map_id = 106;
UPDATE map_config SET map_name = 'Vòng lặp vô tận' WHERE map_id = 110;
UPDATE map_config SET map_name = 'Địa Cung' WHERE map_id = 111;

-- Fix map_portal names
UPDATE map_portal SET portal_name = 'Làng Khởi Đầu → Làng Lá' WHERE portal_id = 1;
UPDATE map_portal SET portal_name = 'Làng Lá → Làng Khởi Đầu' WHERE portal_id = 2;
UPDATE map_portal SET portal_name = 'Làng Lá → Đồng Cỏ Tenchi' WHERE portal_id = 3;
UPDATE map_portal SET portal_name = 'Đồng Cỏ Tenchi → Làng Lá' WHERE portal_id = 4;
UPDATE map_portal SET portal_name = 'Đồng Cỏ Tenchi → Rừng Kumogakure' WHERE portal_id = 5;
UPDATE map_portal SET portal_name = 'Rừng Kumogakure → Đồng Cỏ Tenchi' WHERE portal_id = 6;
UPDATE map_portal SET portal_name = 'Rừng Kumogakure → Nghĩa Địa Bỏ Hoang' WHERE portal_id = 7;
UPDATE map_portal SET portal_name = 'Nghĩa Địa Bỏ Hoang → Rừng Kumogakure' WHERE portal_id = 8;
UPDATE map_portal SET portal_name = 'Nghĩa Địa Bỏ Hoang → Chiến Trường Cổ' WHERE portal_id = 9;
UPDATE map_portal SET portal_name = 'Chiến Trường Cổ → Nghĩa Địa Bỏ Hoang' WHERE portal_id = 10;
UPDATE map_portal SET portal_name = 'Chiến Trường Cổ → Đồi Cát' WHERE portal_id = 11;
UPDATE map_portal SET portal_name = 'Đồi Cát → Chiến Trường Cổ' WHERE portal_id = 12;
UPDATE map_portal SET portal_name = 'Đồi Cát → Sa mạc Sunagakure' WHERE portal_id = 13;
UPDATE map_portal SET portal_name = 'Sa mạc Sunagakure → Đồi Cát' WHERE portal_id = 14;
UPDATE map_portal SET portal_name = 'Sa mạc Sunagakure → Làng Cát' WHERE portal_id = 15;
UPDATE map_portal SET portal_name = 'Làng Cát → Sa mạc Sunagakure' WHERE portal_id = 16;
UPDATE map_portal SET portal_name = 'Làng Cát → Vách Chigiri' WHERE portal_id = 17;
UPDATE map_portal SET portal_name = 'Vách Chigiri → Làng Cát' WHERE portal_id = 18;
UPDATE map_portal SET portal_name = 'Vách Chigiri → Núi Kirigakure' WHERE portal_id = 19;
UPDATE map_portal SET portal_name = 'Núi Kirigakure → Vách Chigiri' WHERE portal_id = 20;
UPDATE map_portal SET portal_name = 'Núi Kirigakure → Cánh Đồng Kaminari' WHERE portal_id = 21;
UPDATE map_portal SET portal_name = 'Cánh Đồng Kaminari → Núi Kirigakure' WHERE portal_id = 22;
UPDATE map_portal SET portal_name = 'Cánh Đồng Kaminari → Thung Lũng Chết' WHERE portal_id = 23;
UPDATE map_portal SET portal_name = 'Thung Lũng Chết → Cánh Đồng Kaminari' WHERE portal_id = 24;
UPDATE map_portal SET portal_name = 'Thung Lũng Chết → Đồi Hoang' WHERE portal_id = 25;
UPDATE map_portal SET portal_name = 'Đồi Hoang → Thung Lũng Chết' WHERE portal_id = 26;
UPDATE map_portal SET portal_name = 'Đồi Hoang → Hầm Núi Mizu' WHERE portal_id = 27;
UPDATE map_portal SET portal_name = 'Hầm Núi Mizu → Đồi Hoang' WHERE portal_id = 28;
UPDATE map_portal SET portal_name = 'Hầm Núi Mizu → Làng Sương Mù' WHERE portal_id = 29;
UPDATE map_portal SET portal_name = 'Làng Sương Mù → Hầm Núi Mizu' WHERE portal_id = 30;
UPDATE map_portal SET portal_name = 'Làng Sương Mù → Làng Cổ' WHERE portal_id = 31;
UPDATE map_portal SET portal_name = 'Làng Cổ → Làng Sương Mù' WHERE portal_id = 32;
UPDATE map_portal SET portal_name = 'Làng Cổ → Vách Đá Ngang' WHERE portal_id = 33;
UPDATE map_portal SET portal_name = 'Vách Đá Ngang → Làng Cổ' WHERE portal_id = 34;
UPDATE map_portal SET portal_name = 'Vách Đá Ngang → Miếu Iwagakure' WHERE portal_id = 35;
UPDATE map_portal SET portal_name = 'Miếu Iwagakure → Vách Đá Ngang' WHERE portal_id = 36;
UPDATE map_portal SET portal_name = 'Miếu Iwagakure → Chân Núi Tsuchi' WHERE portal_id = 37;
UPDATE map_portal SET portal_name = 'Chân Núi Tsuchi → Miếu Iwagakure' WHERE portal_id = 38;
UPDATE map_portal SET portal_name = 'Chân Núi Tsuchi → Rừng Nấm' WHERE portal_id = 39;
UPDATE map_portal SET portal_name = 'Rừng Nấm → Chân Núi Tsuchi' WHERE portal_id = 40;
UPDATE map_portal SET portal_name = 'Rừng Nấm → Dòng Sông Kusagakure' WHERE portal_id = 41;
UPDATE map_portal SET portal_name = 'Dòng Sông Kusagakure → Rừng Nấm' WHERE portal_id = 42;
UPDATE map_portal SET portal_name = 'Dòng Sông Kusagakure → Làng Mây' WHERE portal_id = 43;
UPDATE map_portal SET portal_name = 'Làng Mây → Dòng Sông Kusagakure' WHERE portal_id = 44;
UPDATE map_portal SET portal_name = 'Làng Mây → Núi Hokage' WHERE portal_id = 45;
UPDATE map_portal SET portal_name = 'Núi Hokage → Làng Mây' WHERE portal_id = 46;
UPDATE map_portal SET portal_name = 'Núi Hokage → Làng Đá' WHERE portal_id = 47;
UPDATE map_portal SET portal_name = 'Làng Đá → Núi Hokage' WHERE portal_id = 48;
UPDATE map_portal SET portal_name = 'Làng Đá → Trường Konoha' WHERE portal_id = 49;
UPDATE map_portal SET portal_name = 'Trường Konoha → Làng Đá' WHERE portal_id = 50;
UPDATE map_portal SET portal_name = 'Trường Konoha → Hang Khổ' WHERE portal_id = 51;
UPDATE map_portal SET portal_name = 'Hang Khổ → Trường Konoha' WHERE portal_id = 52;
UPDATE map_portal SET portal_name = 'Hang Khổ → Cầu Kannabi' WHERE portal_id = 53;
UPDATE map_portal SET portal_name = 'Cầu Kannabi → Hang Khổ' WHERE portal_id = 54;
UPDATE map_portal SET portal_name = 'Cầu Kannabi → Đồi trung tâm' WHERE portal_id = 55;
UPDATE map_portal SET portal_name = 'Đồi trung tâm → Cầu Kannabi' WHERE portal_id = 56;
UPDATE map_portal SET portal_name = 'Đồi trung tâm → Thánh Địa Thất Kiếm' WHERE portal_id = 57;
UPDATE map_portal SET portal_name = 'Thánh Địa Thất Kiếm → Đồi trung tâm' WHERE portal_id = 58;
UPDATE map_portal SET portal_name = 'Thánh Địa Thất Kiếm → Thung lũng Tấn Công' WHERE portal_id = 59;
UPDATE map_portal SET portal_name = 'Thung lũng Tấn Công → Thánh Địa Thất Kiếm' WHERE portal_id = 60;
UPDATE map_portal SET portal_name = 'Thung lũng Tấn Công → Chiến trường' WHERE portal_id = 61;
UPDATE map_portal SET portal_name = 'Chiến trường → Thung lũng Tấn Công' WHERE portal_id = 62;
UPDATE map_portal SET portal_name = 'Chiến trường → Cửa phía tây' WHERE portal_id = 63;
UPDATE map_portal SET portal_name = 'Cửa phía tây → Chiến trường' WHERE portal_id = 64;
UPDATE map_portal SET portal_name = 'Cửa phía tây → Cửa phía đông' WHERE portal_id = 65;
UPDATE map_portal SET portal_name = 'Cửa phía đông → Cửa phía tây' WHERE portal_id = 66;
UPDATE map_portal SET portal_name = 'Cửa phía đông → Làng Mưa' WHERE portal_id = 67;
UPDATE map_portal SET portal_name = 'Làng Mưa → Cửa phía đông' WHERE portal_id = 68;
UPDATE map_portal SET portal_name = 'Làng Mưa → Pháo Đài Amega' WHERE portal_id = 69;
UPDATE map_portal SET portal_name = 'Pháo Đài Amega → Làng Mưa' WHERE portal_id = 70;
UPDATE map_portal SET portal_name = 'Pháo Đài Amega → Vùng trũng Kusa' WHERE portal_id = 71;
UPDATE map_portal SET portal_name = 'Vùng trũng Kusa → Pháo Đài Amega' WHERE portal_id = 72;
UPDATE map_portal SET portal_name = 'Vùng trũng Kusa → Lãnh Địa thiên thần' WHERE portal_id = 73;
UPDATE map_portal SET portal_name = 'Lãnh Địa thiên thần → Vùng trũng Kusa' WHERE portal_id = 74;
UPDATE map_portal SET portal_name = 'Lãnh Địa thiên thần → Căn cứ Akatsuki' WHERE portal_id = 75;
UPDATE map_portal SET portal_name = 'Căn cứ Akatsuki → Lãnh Địa thiên thần' WHERE portal_id = 76;
UPDATE map_portal SET portal_name = 'Làng Khởi Đầu → Địa cung (sơ cấp)' WHERE portal_id = 77;
UPDATE map_portal SET portal_name = 'Địa cung (sơ cấp) → Làng Khởi Đầu' WHERE portal_id = 78;
UPDATE map_portal SET portal_name = 'Làng Khởi Đầu → Địa cung (trung cấp)' WHERE portal_id = 79;
UPDATE map_portal SET portal_name = 'Địa cung (trung cấp) → Làng Khởi Đầu' WHERE portal_id = 80;
UPDATE map_portal SET portal_name = 'Làng Khởi Đầu → Địa cung (cao cấp)' WHERE portal_id = 81;
UPDATE map_portal SET portal_name = 'Địa cung (cao cấp) → Làng Khởi Đầu' WHERE portal_id = 82;
UPDATE map_portal SET portal_name = 'Làng Khởi Đầu → Địa cung (thượng cấp)' WHERE portal_id = 83;
UPDATE map_portal SET portal_name = 'Địa cung (thượng cấp) → Làng Khởi Đầu' WHERE portal_id = 84;
UPDATE map_portal SET portal_name = 'Đồi trung tâm → Hang Vô Thú' WHERE portal_id = 85;
UPDATE map_portal SET portal_name = 'Hang Vô Thú → Đồi trung tâm' WHERE portal_id = 86;
UPDATE map_portal SET portal_name = 'Cánh Đồng Kaminari → Hầm bí mật' WHERE portal_id = 87;
UPDATE map_portal SET portal_name = 'Hầm bí mật → Cánh Đồng Kaminari' WHERE portal_id = 88;
UPDATE map_portal SET portal_name = 'Làng Lá → Khu luyện tập' WHERE portal_id = 89;
UPDATE map_portal SET portal_name = 'Khu luyện tập → Làng Lá' WHERE portal_id = 90;
UPDATE map_portal SET portal_name = 'Cầu Kannabi → Vòng Lặp Ảo Tưởng' WHERE portal_id = 91;
UPDATE map_portal SET portal_name = 'Vòng Lặp Ảo Tưởng → Cầu Kannabi' WHERE portal_id = 92;
UPDATE map_portal SET portal_name = 'Hang Vô Thú → Hang Vô Thú (cấp 1)' WHERE portal_id = 93;
UPDATE map_portal SET portal_name = 'Hang Vô Thú (cấp 1) → Hang Vô Thú' WHERE portal_id = 94;
UPDATE map_portal SET portal_name = 'Hang Vô Thú → Hang Vô Thú (cấp 2)' WHERE portal_id = 95;
UPDATE map_portal SET portal_name = 'Hang Vô Thú (cấp 2) → Hang Vô Thú' WHERE portal_id = 96;
UPDATE map_portal SET portal_name = 'Hang Vô Thú → Hang Vô Thú (cấp 3)' WHERE portal_id = 97;
UPDATE map_portal SET portal_name = 'Hang Vô Thú (cấp 3) → Hang Vô Thú' WHERE portal_id = 98;
UPDATE map_portal SET portal_name = 'Hang Khổ → Hang Gamaken' WHERE portal_id = 99;
UPDATE map_portal SET portal_name = 'Hang Gamaken → Hang Khổ' WHERE portal_id = 100;
UPDATE map_portal SET portal_name = 'Hang Khổ → Hang Gamatatsu' WHERE portal_id = 101;
UPDATE map_portal SET portal_name = 'Hang Gamatatsu → Hang Khổ' WHERE portal_id = 102;
UPDATE map_portal SET portal_name = 'Hang Khổ → Hang Gama Armored' WHERE portal_id = 103;
UPDATE map_portal SET portal_name = 'Hang Gama Armored → Hang Khổ' WHERE portal_id = 104;
UPDATE map_portal SET portal_name = 'Hang Khổ → Hang Gamabunta' WHERE portal_id = 105;
UPDATE map_portal SET portal_name = 'Hang Gamabunta → Hang Khổ' WHERE portal_id = 106;
UPDATE map_portal SET portal_name = 'Hang Khổ → Hang Gamahiro' WHERE portal_id = 107;
UPDATE map_portal SET portal_name = 'Hang Gamahiro → Hang Khổ' WHERE portal_id = 108;
UPDATE map_portal SET portal_name = 'Cửa phía đông → Chiến trường phó bản' WHERE portal_id = 109;
UPDATE map_portal SET portal_name = 'Chiến trường phó bản → Cửa phía đông' WHERE portal_id = 110;
UPDATE map_portal SET portal_name = 'Vào Vòng lặp vô tận' WHERE portal_id = 111;
UPDATE map_portal SET portal_name = 'Vào Địa Cung' WHERE portal_id = 112;

SELECT 'map_config names fixed:', COUNT(*) FROM map_config;
SELECT 'map_portal names fixed:', COUNT(*) FROM map_portal;
