import sys
import mysql.connector

# Ensure stdout can handle UTF-8
sys.stdout.reconfigure(encoding='utf-8')

conn = mysql.connector.connect(
    host='127.0.0.1',
    user='root',
    database='gamedb',
    charset='utf8mb4',
    collation='utf8mb4_general_ci'
)
c = conn.cursor()

map_names = [
    (0, 'Làng Khởi Đầu'),
    (6, 'Địa cung (sơ cấp)'),
    (7, 'Địa cung (trung cấp)'),
    (18, 'Địa cung (cao cấp)'),
    (19, 'Địa cung (thượng cấp)'),
    (56, 'Đồi trung tâm'),
    (57, 'Thánh Địa Thất Kiếm'),
    (58, 'Hang Vô Thú'),
    (59, 'Làng Cát'),
    (60, 'Làng Sương Mù'),
    (61, 'Vách Chigiri'),
    (62, 'Núi Kirigakure'),
    (63, 'Cánh Đồng Kaminari'),
    (64, 'Thung Lũng Chết'),
    (65, 'Đồi Hoang'),
    (66, 'Hầm Núi Mizu'),
    (67, 'Hầm bí mật'),
    (68, 'Làng Cổ'),
    (69, 'Làng Mây'),
    (70, 'Vách Đá Ngang'),
    (71, 'Miếu Iwagakure'),
    (72, 'Chân Núi Tsuchi'),
    (73, 'Rừng Nấm'),
    (74, 'Dòng Sông Kusagakure'),
    (75, 'Làng Lá'),
    (76, 'Đồng Cỏ Tenchi'),
    (77, 'Rừng Kumogakure'),
    (78, 'Nghĩa Địa Bỏ Hoang'),
    (79, 'Chiến Trường Cổ'),
    (80, 'Đồi Cát'),
    (81, 'Sa mạc Sunagakure'),
    (82, 'Núi Hokage'),
    (83, 'Thung lũng Tấn Công'),
    (84, 'Khu luyện tập'),
    (85, 'Làng Đá'),
    (86, 'Trường Konoha'),
    (87, 'Hang Khổ'),
    (88, 'Cầu Kannabi'),
    (89, 'Vòng Lặp Ảo Tưởng'),
    (90, 'Hang Vô Thú (cấp 1)'),
    (91, 'Hang Vô Thú (cấp 2)'),
    (92, 'Hang Vô Thú (cấp 3)'),
    (93, 'Hang Gamaken'),
    (94, 'Hang Gamatatsu'),
    (95, 'Hang Gama Armored'),
    (96, 'Hang Gamabunta'),
    (97, 'Hang Gamahiro'),
    (98, 'Chiến trường'),
    (99, 'Cửa phía tây'),
    (100, 'Cửa phía đông'),
    (101, 'Chiến trường phó bản'),
    (102, 'Làng Mưa'),
    (103, 'Pháo Đài Amega'),
    (104, 'Vùng trũng Kusa'),
    (105, 'Lãnh Địa thiên thần'),
    (106, 'Căn cứ Akatsuki'),
    (110, 'Vòng lặp vô tận'),
    (111, 'Địa Cung'),
]

portal_names = [
    (1, 'Làng Khởi Đầu → Làng Lá'),
    (2, 'Làng Lá → Làng Khởi Đầu'),
    (3, 'Làng Lá → Đồng Cỏ Tenchi'),
    (4, 'Đồng Cỏ Tenchi → Làng Lá'),
    (5, 'Đồng Cỏ Tenchi → Rừng Kumogakure'),
    (6, 'Rừng Kumogakure → Đồng Cỏ Tenchi'),
    (7, 'Rừng Kumogakure → Nghĩa Địa Bỏ Hoang'),
    (8, 'Nghĩa Địa Bỏ Hoang → Rừng Kumogakure'),
    (9, 'Nghĩa Địa Bỏ Hoang → Chiến Trường Cổ'),
    (10, 'Chiến Trường Cổ → Nghĩa Địa Bỏ Hoang'),
    (11, 'Chiến Trường Cổ → Đồi Cát'),
    (12, 'Đồi Cát → Chiến Trường Cổ'),
    (13, 'Đồi Cát → Sa mạc Sunagakure'),
    (14, 'Sa mạc Sunagakure → Đồi Cát'),
    (15, 'Sa mạc Sunagakure → Làng Cát'),
    (16, 'Làng Cát → Sa mạc Sunagakure'),
    (17, 'Làng Cát → Vách Chigiri'),
    (18, 'Vách Chigiri → Làng Cát'),
    (19, 'Vách Chigiri → Núi Kirigakure'),
    (20, 'Núi Kirigakure → Vách Chigiri'),
    (21, 'Núi Kirigakure → Cánh Đồng Kaminari'),
    (22, 'Cánh Đồng Kaminari → Núi Kirigakure'),
    (23, 'Cánh Đồng Kaminari → Thung Lũng Chết'),
    (24, 'Thung Lũng Chết → Cánh Đồng Kaminari'),
    (25, 'Thung Lũng Chết → Đồi Hoang'),
    (26, 'Đồi Hoang → Thung Lũng Chết'),
    (27, 'Đồi Hoang → Hầm Núi Mizu'),
    (28, 'Hầm Núi Mizu → Đồi Hoang'),
    (29, 'Hầm Núi Mizu → Làng Sương Mù'),
    (30, 'Làng Sương Mù → Hầm Núi Mizu'),
    (31, 'Làng Sương Mù → Làng Cổ'),
    (32, 'Làng Cổ → Làng Sương Mù'),
    (33, 'Làng Cổ → Vách Đá Ngang'),
    (34, 'Vách Đá Ngang → Làng Cổ'),
    (35, 'Vách Đá Ngang → Miếu Iwagakure'),
    (36, 'Miếu Iwagakure → Vách Đá Ngang'),
    (37, 'Miếu Iwagakure → Chân Núi Tsuchi'),
    (38, 'Chân Núi Tsuchi → Miếu Iwagakure'),
    (39, 'Chân Núi Tsuchi → Rừng Nấm'),
    (40, 'Rừng Nấm → Chân Núi Tsuchi'),
    (41, 'Rừng Nấm → Dòng Sông Kusagakure'),
    (42, 'Dòng Sông Kusagakure → Rừng Nấm'),
    (43, 'Dòng Sông Kusagakure → Làng Mây'),
    (44, 'Làng Mây → Dòng Sông Kusagakure'),
    (45, 'Làng Mây → Núi Hokage'),
    (46, 'Núi Hokage → Làng Mây'),
    (47, 'Núi Hokage → Làng Đá'),
    (48, 'Làng Đá → Núi Hokage'),
    (49, 'Làng Đá → Trường Konoha'),
    (50, 'Trường Konoha → Làng Đá'),
    (51, 'Trường Konoha → Hang Khổ'),
    (52, 'Hang Khổ → Trường Konoha'),
    (53, 'Hang Khổ → Cầu Kannabi'),
    (54, 'Cầu Kannabi → Hang Khổ'),
    (55, 'Cầu Kannabi → Đồi trung tâm'),
    (56, 'Đồi trung tâm → Cầu Kannabi'),
    (57, 'Đồi trung tâm → Thánh Địa Thất Kiếm'),
    (58, 'Thánh Địa Thất Kiếm → Đồi trung tâm'),
    (59, 'Thánh Địa Thất Kiếm → Thung lũng Tấn Công'),
    (60, 'Thung lũng Tấn Công → Thánh Địa Thất Kiếm'),
    (61, 'Thung lũng Tấn Công → Chiến trường'),
    (62, 'Chiến trường → Thung lũng Tấn Công'),
    (63, 'Chiến trường → Cửa phía tây'),
    (64, 'Cửa phía tây → Chiến trường'),
    (65, 'Cửa phía tây → Cửa phía đông'),
    (66, 'Cửa phía đông → Cửa phía tây'),
    (67, 'Cửa phía đông → Làng Mưa'),
    (68, 'Làng Mưa → Cửa phía đông'),
    (69, 'Làng Mưa → Pháo Đài Amega'),
    (70, 'Pháo Đài Amega → Làng Mưa'),
    (71, 'Pháo Đài Amega → Vùng trũng Kusa'),
    (72, 'Vùng trũng Kusa → Pháo Đài Amega'),
    (73, 'Vùng trũng Kusa → Lãnh Địa thiên thần'),
    (74, 'Lãnh Địa thiên thần → Vùng trũng Kusa'),
    (75, 'Lãnh Địa thiên thần → Căn cứ Akatsuki'),
    (76, 'Căn cứ Akatsuki → Lãnh Địa thiên thần'),
    (77, 'Làng Khởi Đầu → Địa cung (sơ cấp)'),
    (78, 'Địa cung (sơ cấp) → Làng Khởi Đầu'),
    (79, 'Làng Khởi Đầu → Địa cung (trung cấp)'),
    (80, 'Địa cung (trung cấp) → Làng Khởi Đầu'),
    (81, 'Làng Khởi Đầu → Địa cung (cao cấp)'),
    (82, 'Địa cung (cao cấp) → Làng Khởi Đầu'),
    (83, 'Làng Khởi Đầu → Địa cung (thượng cấp)'),
    (84, 'Địa cung (thượng cấp) → Làng Khởi Đầu'),
    (85, 'Đồi trung tâm → Hang Vô Thú'),
    (86, 'Hang Vô Thú → Đồi trung tâm'),
    (87, 'Cánh Đồng Kaminari → Hầm bí mật'),
    (88, 'Hầm bí mật → Cánh Đồng Kaminari'),
    (89, 'Làng Lá → Khu luyện tập'),
    (90, 'Khu luyện tập → Làng Lá'),
    (91, 'Cầu Kannabi → Vòng Lặp Ảo Tưởng'),
    (92, 'Vòng Lặp Ảo Tưởng → Cầu Kannabi'),
    (93, 'Hang Vô Thú → Hang Vô Thú (cấp 1)'),
    (94, 'Hang Vô Thú (cấp 1) → Hang Vô Thú'),
    (95, 'Hang Vô Thú → Hang Vô Thú (cấp 2)'),
    (96, 'Hang Vô Thú (cấp 2) → Hang Vô Thú'),
    (97, 'Hang Vô Thú → Hang Vô Thú (cấp 3)'),
    (98, 'Hang Vô Thú (cấp 3) → Hang Vô Thú'),
    (99, 'Hang Khổ → Hang Gamaken'),
    (100, 'Hang Gamaken → Hang Khổ'),
    (101, 'Hang Khổ → Hang Gamatatsu'),
    (102, 'Hang Gamatatsu → Hang Khổ'),
    (103, 'Hang Khổ → Hang Gama Armored'),
    (104, 'Hang Gama Armored → Hang Khổ'),
    (105, 'Hang Khổ → Hang Gamabunta'),
    (106, 'Hang Gamabunta → Hang Khổ'),
    (107, 'Hang Khổ → Hang Gamahiro'),
    (108, 'Hang Gamahiro → Hang Khổ'),
    (109, 'Cửa phía đông → Chiến trường phó bản'),
    (110, 'Chiến trường phó bản → Cửa phía đông'),
    (111, 'Vào Vòng lặp vô tận'),
    (112, 'Vào Địa Cung'),
]

# Update map_config
for map_id, name in map_names:
    c.execute("UPDATE map_config SET map_name=%s WHERE map_id=%s", (name, map_id))
print(f"Updated {len(map_names)} map_config rows")

# Update map_portal
for portal_id, name in portal_names:
    c.execute("UPDATE map_portal SET portal_name=%s WHERE portal_id=%s", (name, portal_id))
print(f"Updated {len(portal_names)} map_portal rows")

conn.commit()

# Verify
c.execute("SELECT map_id, map_name FROM map_config ORDER BY map_id LIMIT 5")
print("map_config sample:")
for row in c.fetchall():
    print(f"  {row[0]}: {row[1]}")

c.execute("SELECT portal_id, portal_name FROM map_portal LIMIT 5")
print("map_portal sample:")
for row in c.fetchall():
    print(f"  {row[0]}: {row[1]}")

conn.close()
print("Done!")
