import os
import sys

def fix_chapter2():
    sys.stdout.reconfigure(encoding='utf-8')
    filepath = r"c:\Hub\DoAn\docs\CHUONG2_BAO_CAO.md"
    
    if not os.path.exists(filepath):
        print(f"Error: {filepath} not found.")
        return
        
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
        
    # 1. Update Figure 2.2 General Use Case to use image9.png instead of image10.png
    content = content.replace(
        "![Biểu đồ Use Case tổng quát hệ thống Mutants Arena](extracted_images/image10.png)\n\n*Hình 2.2. Biểu đồ Use Case tổng quát hệ thống Mutants Arena*",
        "![Biểu đồ Use Case tổng quát hệ thống Mutants Arena](extracted_images/image9.png)\n\n*Hình 2.2. Biểu đồ Use Case tổng quát hệ thống Mutants Arena*"
    )
    
    # 2. Add detailed use case diagrams under UC01 to UC16
    uc_edits = {
        "##### UC01 — Đăng ký tài khoản\n*   **Actor chính:** Khách.\n*   **Mô tả:** Khách tạo tài khoản mới để bắt đầu sử dụng hệ thống. Hệ thống mã hóa mật khẩu và lưu tài khoản vào cơ sở dữ liệu.\n*   **Luồng chính:\n    1.  Khách mở màn hình đăng ký từ giao diện chính.\n    2.  Hệ thống hiển thị biểu mẫu gồm tên đăng nhập, email và mật khẩu.\n    3.  Khách nhập thông tin và xác nhận.\n    4.  Server kiểm tra tính hợp lệ và sự tồn tại của tên đăng nhập/email.\n    5.  Server mã hóa mật khẩu (BCrypt), lưu tài khoản và thông báo đăng ký thành công.\n*   **Luồng phụ / Ngoại lệ:** Tên đăng nhập/email đã tồn tại hoặc thiếu trường bắt buộc → Hệ thống hiển thị lỗi tương ứng trên UI.":
        "##### UC01 — Đăng ký tài khoản\n*   **Actor chính:** Khách.\n*   **Mô tả:** Khách tạo tài khoản mới để bắt đầu sử dụng hệ thống. Hệ thống mã hóa mật khẩu và lưu tài khoản vào cơ sở dữ liệu.\n*   **Luồng chính:\n    1.  Khách mở màn hình đăng ký từ giao diện chính.\n    2.  Hệ thống hiển thị biểu mẫu gồm tên đăng nhập, email và mật khẩu.\n    3.  Khách nhập thông tin và xác nhận.\n    4.  Server kiểm tra tính hợp lệ và sự tồn tại của tên đăng nhập/email.\n    5.  Server mã hóa mật khẩu (BCrypt), lưu tài khoản và thông báo đăng ký thành công.\n*   **Luồng phụ / Ngoại lệ:** Tên đăng nhập/email đã tồn tại hoặc thiếu trường bắt buộc → Hệ thống hiển thị lỗi tương ứng trên UI.\n\n![Biểu đồ Use case chức năng Đăng ký tài khoản](extracted_images/image10.png)\n\n*Hình 2.3. Biểu đồ Use case chức năng Đăng ký tài khoản*",

        "##### UC02 — Đăng nhập và vào game\n*   **Actor chính:** Khách, Người chơi.\n*   **Mô tả:** Người chơi xác thực tài khoản qua JWT, chọn nhân vật và kết nối vào thế giới game thời gian thực.\n*   **Luồng chính:\n    1.  Người dùng nhập tên đăng nhập và mật khẩu trên giao diện.\n    2.  Hệ thống xác thực mật khẩu hash.\n    3.  Hệ thống cấp token JWT và tải danh sách nhân vật.\n    4.  Người chơi chọn hoặc tạo nhân vật mới.\n    5.  Client dùng token JWT kết nối đến Gameplay Server (NGO).\n    6.  Gameplay Server duyệt kết nối (Connection Approval) và spawn nhân vật vào map.\n*   **Luồng phụ / Ngoại lệ:** Sai mật khẩu hoặc lỗi kết nối máy chủ → Hệ thống báo lỗi và cho phép thử lại.":
        "##### UC02 — Đăng nhập và vào game\n*   **Actor chính:** Khách, Người chơi.\n*   **Mô tả:** Người chơi xác thực tài khoản qua JWT, chọn nhân vật và kết nối vào thế giới game thời gian thực.\n*   **Luồng chính:\n    1.  Người dùng nhập tên đăng nhập và mật khẩu trên giao diện.\n    2.  Hệ thống xác thực mật khẩu hash.\n    3.  Hệ thống cấp token JWT và tải danh sách nhân vật.\n    4.  Người chơi chọn hoặc tạo nhân vật mới.\n    5.  Client dùng token JWT kết nối đến Gameplay Server (NGO).\n    6.  Gameplay Server duyệt kết nối (Connection Approval) và spawn nhân vật vào map.\n*   **Luồng phụ / Ngoại lệ:** Sai mật khẩu hoặc lỗi kết nối máy chủ → Hệ thống báo lỗi và cho phép thử lại.\n\n![Biểu đồ Use case chức năng Đăng nhập và vào game](extracted_images/image11.png)\n\n*Hình 2.4. Biểu đồ Use case chức năng Đăng nhập và vào game*",

        "##### UC03 — Di chuyển và chuyển map\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi điều khiển nhân vật di chuyển và đi qua portal để chuyển sang map hoặc khu vực mới.\n*   **Luồng chính:\n    1.  Người chơi di chuyển nhân vật đến gần portal trên bản đồ.\n    2.  Hệ thống hiển thị gợi ý tương tác portal.\n    3.  Người chơi xác nhận di chuyển.\n    4.  Server kiểm tra điều kiện map đích (cấp độ, nhiệm vụ).\n    5.  Server tải bản đồ mới và cập nhật zone, vị trí xuất hiện của nhân vật.\n*   **Luồng phụ / Ngoại lệ:** Chưa đạt cấp độ yêu cầu hoặc chưa hoàn thành quest tiền đề → Hệ thống hiển thị thông báo khóa map.":
        "##### UC03 — Di chuyển và chuyển map\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi điều khiển nhân vật di chuyển và đi qua portal để chuyển sang map hoặc khu vực mới.\n*   **Luồng chính:\n    1.  Người chơi di chuyển nhân vật đến gần portal trên bản đồ.\n    2.  Hệ thống hiển thị gợi ý tương tác portal.\n    3.  Người chơi xác nhận di chuyển.\n    4.  Server kiểm tra điều kiện map đích (cấp độ, nhiệm vụ).\n    5.  Server tải bản đồ mới và cập nhật zone, vị trí xuất hiện của nhân vật.\n*   **Luồng phụ / Ngoại lệ:** Chưa đạt cấp độ yêu cầu hoặc chưa hoàn thành quest tiền đề → Hệ thống hiển thị thông báo khóa map.\n\n![Biểu đồ Use case chức năng Di chuyển và chuyển map](extracted_images/image12.png)\n\n*Hình 2.5. Biểu đồ Use case chức năng Di chuyển và chuyển map*",

        "##### UC04 — Chiến đấu và sử dụng kỹ năng\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi thực hiện tấn công hoặc dùng kỹ năng lên quái vật. Server tính toán và đồng bộ máu.\n*   **Luồng chính:\n    1.  Người chơi di chuyển và nhấn phím dùng đòn đánh thường hoặc kỹ năng.\n    2.  Client gửi input lên Gameplay Server qua ServerRpc.\n    3.  Server kiểm tra cooldown, MP, hitbox và tính toán sát thương (bao gồm tương khắc nguyên tố).\n    4.  Server trừ máu mục tiêu và cập nhật trạng thái qua NetworkVariable.\n    5.  Các client đồng bộ animation và HUD hiển thị.\n*   **Luồng phụ / Ngoại lệ:** Kỹ năng đang hồi chiêu hoặc không đủ mana → Hệ thống từ chối thi triển.":
        "##### UC04 — Chiến đấu và sử dụng kỹ năng\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi thực hiện tấn công hoặc dùng kỹ năng lên quái vật. Server tính toán và đồng bộ máu.\n*   **Luồng chính:\n    1.  Người chơi di chuyển và nhấn phím dùng đòn đánh thường hoặc kỹ năng.\n    2.  Client gửi input lên Gameplay Server qua ServerRpc.\n    3.  Server kiểm tra cooldown, MP, hitbox và tính toán sát thương (bao gồm tương khắc nguyên tố).\n    4.  Server trừ máu mục tiêu và cập nhật trạng thái qua NetworkVariable.\n    5.  Các client đồng bộ animation và HUD hiển thị.\n*   **Luồng phụ / Ngoại lệ:** Kỹ năng đang hồi chiêu hoặc không đủ mana → Hệ thống từ chối thi triển.\n\n![Biểu đồ Use case chức năng Chiến đấu và sử dụng kỹ năng](extracted_images/image13.png)\n\n*Hình 2.6. Biểu đồ Use case chức năng Chiến đấu và sử dụng kỹ năng*",

        "##### UC05 — Quản lý túi đồ và trang bị\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi xem, sử dụng vật phẩm tiêu hao hoặc trang bị/tháo vũ khí trong inventory.\n*   **Luồng chính:\n    1.  Người chơi mở giao diện túi đồ (Inventory).\n    2.  Client hiển thị danh sách vật phẩm nạp từ API.\n    3.  Người chơi click dùng vật phẩm tiêu hao hoặc kéo thả trang bị vào slot.\n    4.  API Server cập nhật dữ liệu `inventory`/`equipment` trong DB.\n    5.  Client cập nhật chỉ số nhân vật và HUD UI.\n*   **Luồng phụ / Ngoại lệ:** Túi đồ đã đầy → Không thể nhận thêm vật phẩm mới từ phó bản hoặc NPC.":
        "##### UC05 — Quản lý túi đồ và trang bị\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi xem, sử dụng vật phẩm tiêu hao hoặc trang bị/tháo vũ khí trong inventory.\n*   **Luồng chính:\n    1.  Người chơi mở giao diện túi đồ (Inventory).\n    2.  Client hiển thị danh sách vật phẩm nạp từ API.\n    3.  Người chơi click dùng vật phẩm tiêu hao hoặc kéo thả trang bị vào slot.\n    4.  API Server cập nhật dữ liệu `inventory`/`equipment` trong DB.\n    5.  Client cập nhật chỉ số nhân vật và HUD UI.\n*   **Luồng phụ / Ngoại lệ:** Túi đồ đã đầy → Không thể nhận thêm vật phẩm mới từ phó bản hoặc NPC.\n\n![Biểu đồ Use case chức năng Quản lý túi đồ và trang bị](extracted_images/image14.png)\n\n*Hình 2.7. Biểu đồ Use case chức năng Quản lý túi đồ và trang bị*",

        "##### UC06 — Nâng cấp trang bị\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi nâng cấp (cường hóa) trang bị tại NPC thợ rèn bằng đá cường hóa và bạc.\n*   **Luồng chính:\n    1.  Người chơi tương tác với Blacksmith và chọn chức năng cường hóa.\n    2.  Chọn trang bị và đặt vật liệu (đá cường hóa, Lucky Stone, Protection Stone).\n    3.  Client gửi yêu cầu cường hóa kèm chỉ mục slot vật liệu.\n    4.  Server kiểm tra tính hợp pháp của stack nguyên liệu và bạc.\n    5.  Server tính toán tỷ lệ thành công và cập nhật cấp trang bị (`upgradeLevel`).\n*   **Luồng phụ / Ngoại lệ:** Thất bại và không dùng đá bảo vệ → Trang bị bị tụt cấp theo cấu hình `failPolicy`.":
        "##### UC06 — Nâng cấp trang bị\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi nâng cấp (cường hóa) trang bị tại NPC thợ rèn bằng đá cường hóa và bạc.\n*   **Luồng chính:\n    1.  Người chơi tương tác với Blacksmith và chọn chức năng cường hóa.\n    2.  Chọn trang bị và đặt vật liệu (đá cường hóa, Lucky Stone, Protection Stone).\n    3.  Client gửi yêu cầu cường hóa kèm chỉ mục slot vật liệu.\n    4.  Server kiểm tra tính hợp pháp của stack nguyên liệu và bạc.\n    5.  Server tính toán tỷ lệ thành công và cập nhật cấp trang bị (`upgradeLevel`).\n*   **Luồng phụ / Ngoại lệ:** Thất bại và không dùng đá bảo vệ → Trang bị bị tụt cấp theo cấu hình `failPolicy`.\n\n![Biểu đồ Use case chức năng Nâng cấp trang bị](extracted_images/image15.png)\n\n*Hình 2.8. Biểu đồ Use case chức năng Nâng cấp trang bị*",

        "##### UC07 — Phát triển Gene và Hybrid\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi nâng cấp cấp bậc Gene chính, Gene phụ và tiến hành dung hợp Hybrid Gene để đột phá sức mạnh.\n*   **Luồng chính:\n    1.  Người chơi mở giao diện Gene Forge.\n    2.  Nâng cấp Gene chính hoặc chọn/nâng Gene phụ theo cặp tương sinh (Hỏa-Thổ, Thủy-Mộc, Kim-Phong).\n    3.  Khi cả Gene chính và Gene phụ đạt Tier 5, người chơi tiến hành dung hợp.\n    4.  Server trừ nguyên liệu (Fusion Core), vàng và chuyển nhân vật sang trạng thái Hybrid.\n    5.  Mở khóa bộ kỹ năng Hybrid mới và cộng dồn chỉ số.\n*   **Luồng phụ / Ngoại lệ:** Thiếu nguyên liệu hoặc chọn sai cặp nguyên tố phụ → Hệ thống báo lỗi.":
        "##### UC07 — Phát triển Gene và Hybrid\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi nâng cấp cấp bậc Gene chính, Gene phụ và tiến hành dung hợp Hybrid Gene để đột phá sức mạnh.\n*   **Luồng chính:\n    1.  Người chơi mở giao diện Gene Forge.\n    2.  Nâng cấp Gene chính hoặc chọn/nâng Gene phụ theo cặp tương sinh (Hỏa-Thổ, Thủy-Mộc, Kim-Phong).\n    3.  Khi cả Gene chính và Gene phụ đạt Tier 5, người chơi tiến hành dung hợp.\n    4.  Server trừ nguyên liệu (Fusion Core), vàng và chuyển nhân vật sang trạng thái Hybrid.\n    5.  Mở khóa bộ kỹ năng Hybrid mới và cộng dồn chỉ số.\n*   **Luồng phụ / Ngoại lệ:** Thiếu nguyên liệu hoặc chọn sai cặp nguyên tố phụ → Hệ thống báo lỗi.\n\n![Biểu đồ Use case chức năng Phát triển Gene và Hybrid](extracted_images/image16.png)\n\n*Hình 2.9. Biểu đồ Use case chức năng Phát triển Gene và Hybrid*",

        "##### UC08 — Phân bổ tiềm năng và kỹ năng\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi phân bổ điểm thuộc tính (tiềm năng) và nâng cấp cấp độ kỹ năng khi lên cấp.\n*   **Luồng chính:\n    1.  Người chơi mở bảng thông tin nhân vật.\n    2.  Cộng điểm vào các chỉ số: Sức mạnh, Thể chất, Trí tuệ, Nhanh nhẹn.\n    3.  Hoặc cộng điểm nâng cấp các skill nguyên tố.\n    4.  Client gửi yêu cầu lưu chỉ số lên API Server.\n    5.  Server cập nhật dữ liệu nhân vật và đồng bộ NetworkVariable chỉ số.\n*   **Luồng phụ / Ngoại lệ:** Không đủ điểm tiềm năng hoặc cấp kỹ năng đạt giới hạn tối đa → Nút cộng điểm bị vô hiệu hóa.":
        "##### UC08 — Phân bổ tiềm năng và kỹ năng\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi phân bổ điểm thuộc tính (tiềm năng) và nâng cấp cấp độ kỹ năng khi lên cấp.\n*   **Luồng chính:\n    1.  Người chơi mở bảng thông tin nhân vật.\n    2.  Cộng điểm vào các chỉ số: Sức mạnh, Thể chất, Trí tuệ, Nhanh nhẹn.\n    3.  Hoặc cộng điểm nâng cấp các skill nguyên tố.\n    4.  Client gửi yêu cầu lưu chỉ số lên API Server.\n    5.  Server cập nhật dữ liệu nhân vật và đồng bộ NetworkVariable chỉ số.\n*   **Luồng phụ / Ngoại lệ:** Không đủ điểm tiềm năng hoặc cấp kỹ năng đạt giới hạn tối đa → Nút cộng điểm bị vô hiệu hóa.\n\n![Biểu đồ Use case chức năng Phân bổ tiềm năng và kỹ năng](extracted_images/image17.png)\n\n*Hình 2.10. Biểu đồ Use case chức năng Phân bổ tiềm năng và kỹ năng*",

        "##### UC09 — Tương tác NPC và mua vật phẩm\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi đối thoại với NPC trên bản đồ để thực hiện giao dịch hoặc dùng dịch vụ reset potential, learn skill.\n*   **Luồng chính:\n    1.  Người chơi di chuyển đến NPC và click tương tác.\n    2.  Hệ thống nạp danh sách dịch vụ động của NPC từ API.\n    3.  Người chơi chọn mở cửa hàng (Shop) và xác nhận mua vật phẩm.\n    4.  Server kiểm tra bạc và slot trống trong túi, thực hiện giao dịch.\n*   **Luồng phụ / Ngoại lệ:** Không đủ bạc hoặc túi đồ đầy → Hệ thống từ chối giao dịch.":
        "##### UC09 — Tương tác NPC và mua vật phẩm\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi đối thoại với NPC trên bản đồ để thực hiện giao dịch hoặc dùng dịch vụ reset potential, learn skill.\n*   **Luồng chính:\n    1.  Người chơi di chuyển đến NPC và click tương tác.\n    2.  Hệ thống nạp danh sách dịch vụ động của NPC từ API.\n    3.  Người chơi chọn mở cửa hàng (Shop) và xác nhận mua vật phẩm.\n    4.  Server kiểm tra bạc và slot trống trong túi, thực hiện giao dịch.\n*   **Luồng phụ / Ngoại lệ:** Không đủ bạc hoặc túi đồ đầy → Hệ thống từ chối giao dịch.\n\n![Biểu đồ Use case chức năng Tương tác NPC và mua vật phẩm](extracted_images/image18.png)\n\n*Hình 2.11. Biểu đồ Use case chức năng Tương tác NPC và mua vật phẩm*",

        "##### UC10 — Quản lý nhiệm vụ\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi nhận nhiệm vụ từ NPC, theo dõi tiến trình trong game và trả quest để nhận thưởng.\n*   **Luồng chính:\n    1.  Người chơi đối thoại với NPC nhiệm vụ để nhận quest.\n    2.  Server cập nhật trạng thái quest thành `Active` và reset tiến trình.\n    3.  Người chơi làm nhiệm vụ (diệt quái, nhặt đồ, gặp NPC). Gameplay Server gửi tiến trình tự động.\n    4.  Đạt đủ điều kiện, người chơi gặp NPC trả quest và nhận vàng, EXP, item.\n*   **Luồng phụ / Ngoại lệ:** Cấp độ nhân vật chưa đủ cấp quest yêu cầu → Quest hiển thị trạng thái bị khóa.":
        "##### UC10 — Quản lý nhiệm vụ\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi nhận nhiệm vụ từ NPC, theo dõi tiến trình trong game và trả quest để nhận thưởng.\n*   **Luồng chính:\n    1.  Người chơi đối thoại với NPC nhiệm vụ để nhận quest.\n    2.  Server cập nhật trạng thái quest thành `Active` và reset tiến trình.\n    3.  Người chơi làm nhiệm vụ (diệt quái, nhặt đồ, gặp NPC). Gameplay Server gửi tiến trình tự động.\n    4.  Đạt đủ điều kiện, người chơi gặp NPC trả quest và nhận vàng, EXP, item.\n*   **Luồng phụ / Ngoại lệ:** Cấp độ nhân vật chưa đủ cấp quest yêu cầu → Quest hiển thị trạng thái bị khóa.\n\n![Biểu đồ Use case chức năng Quản lý nhiệm vụ](extracted_images/image19.png)\n\n*Hình 2.12. Biểu đồ Use case chức năng Quản lý nhiệm vụ*",

        "##### UC11 — Quản lý bạn bè\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi tìm kiếm, kết bạn, chấp nhận yêu cầu và theo dõi danh sách bạn bè.\n*   **Luồng chính:\n    1.  Người chơi mở giao diện bạn bè.\n    2.  Tìm kiếm nhân vật khác theo tên.\n    3.  Gửi yêu cầu kết bạn.\n    4.  Người chơi bên kia nhận thông báo, click chấp nhận hoặc từ chối.\n    5.  API Server cập nhật quan hệ bạn bè trong DB.":
        "##### UC11 — Quản lý bạn bè\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi tìm kiếm, kết bạn, chấp nhận yêu cầu và theo dõi danh sách bạn bè.\n*   **Luồng chính:\n    1.  Người chơi mở giao diện bạn bè.\n    2.  Tìm kiếm nhân vật khác theo tên.\n    3.  Gửi yêu cầu kết bạn.\n    4.  Người chơi bên kia nhận thông báo, click chấp nhận hoặc từ chối.\n    5.  API Server cập nhật quan hệ bạn bè trong DB.\n\n![Biểu đồ Use case chức năng Quản lý bạn bè](extracted_images/image20.png)\n\n*Hình 2.13. Biểu đồ Use case chức năng Quản lý bạn bè*",

        "##### UC12 — Quản lý tổ đội và chat\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi tạo tổ đội (Party) tối đa 4 người để đi phó bản và giao tiếp qua các kênh chat SignalR.\n*   **Luồng chính:\n    1.  Người chơi tạo party hoặc mời người chơi khác qua SignalR PartyHub.\n    2.  Thành viên tham gia party và hiển thị thông tin máu/mana trên HUD.\n    3.  Người chơi gửi tin nhắn lên các kênh chat (Thế giới, Lân cận, Tổ đội, Thầm kín).\n    4.  SignalR ChatHub phân phối tin nhắn đến đúng phạm vi phòng.":
        "##### UC12 — Quản lý tổ đội và chat\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi tạo tổ đội (Party) tối đa 4 người để đi phó bản và giao tiếp qua các kênh chat SignalR.\n*   **Luồng chính:\n    1.  Người chơi tạo party hoặc mời người chơi khác qua SignalR PartyHub.\n    2.  Thành viên tham gia party và hiển thị thông tin máu/mana trên HUD.\n    3.  Người chơi gửi tin nhắn lên các kênh chat (Thế giới, Lân cận, Tổ đội, Thầm kín).\n    4.  SignalR ChatHub phân phối tin nhắn đến đúng phạm vi phòng.\n\n![Biểu đồ Use case chức năng Quản lý tổ đội và chat](extracted_images/image21.png)\n\n*Hình 2.14. Biểu đồ Use case chức năng Quản lý tổ đội và chat*",

        "##### UC13 — Tham gia và hoàn tất phó bản\n*   **Actor chính:** Người chơi, Gameplay Server.\n*   **Mô tả:** Người chơi hoặc party tham gia vượt phó bản wave, tiêu diệt Boss và nhận phần thưởng.\n*   **Luồng chính:\n    1.  Người chơi mở menu phó bản và tạo session.\n    2.  Gameplay Server khởi tạo scene phó bản mạng, spawn quái vật theo wave.\n    3.  Người chơi tiêu diệt hết các wave quái và Boss cuối.\n    4.  Gameplay Server kết thúc session, đánh dấu hoàn thành dungeon.\n    5.  Server gọi API grant reward để phân phối trang bị, mảnh Gene trực tiếp vào túi người chơi.\n*   **Luồng phụ / Ngoại lệ:** Cả đội bị hạ gục trước khi diệt Boss hoặc hết thời gian wave → Thất bại, không được phát thưởng.":
        "##### UC13 — Tham gia và hoàn tất phó bản\n*   **Actor chính:** Người chơi, Gameplay Server.\n*   **Mô tả:** Người chơi hoặc party tham gia vượt phó bản wave, tiêu diệt Boss và nhận phần thưởng.\n*   **Luồng chính:\n    1.  Người chơi mở menu phó bản và tạo session.\n    2.  Gameplay Server khởi tạo scene phó bản mạng, spawn quái vật theo wave.\n    3.  Người chơi tiêu diệt hết các wave quái và Boss cuối.\n    4.  Gameplay Server kết thúc session, đánh dấu hoàn thành dungeon.\n    5.  Server gọi API grant reward để phân phối trang bị, mảnh Gene trực tiếp vào túi người chơi.\n*   **Luồng phụ / Ngoại lệ:** Cả đội bị hạ gục trước khi diệt Boss hoặc hết thời gian wave → Thất bại, không được phát thưởng.\n\n![Biểu đồ Use case chức năng Tham gia và hoàn tất phó bản](extracted_images/image22.png)\n\n*Hình 2.15. Biểu đồ Use case chức năng Tham gia và hoàn tất phó bản*",

        "##### UC14 — Xem leaderboard\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi theo dõi thứ hạng của bản thân và các người chơi khác trên bảng xếp hạng server.\n*   **Luồng chính:\n    1.  Người chơi mở bảng xếp hạng (Leaderboard) trong game.\n    2.  Client gửi yêu cầu lấy dữ liệu xếp hạng từ API.\n    3.  Server trả về danh sách Top 50 theo 5 hạng mục (Cấp độ, Nhiệm vụ, Điểm danh, Phó bản, Vàng).\n    4.  Dữ liệu được nạp từ cache 5 phút để bảo vệ hiệu năng database.":
        "##### UC14 — Xem leaderboard\n*   **Actor chính:** Người chơi.\n*   **Mô tả:** Người chơi theo dõi thứ hạng của bản thân và các người chơi khác trên bảng xếp hạng server.\n*   **Luồng chính:\n    1.  Người chơi mở bảng xếp hạng (Leaderboard) trong game.\n    2.  Client gửi yêu cầu lấy dữ liệu xếp hạng từ API.\n    3.  Server trả về danh sách Top 50 theo 5 hạng mục (Cấp độ, Nhiệm vụ, Điểm danh, Phó bản, Vàng).\n    4.  Dữ liệu được nạp từ cache 5 phút để bảo vệ hiệu năng database.\n\n![Biểu đồ Use case chức năng Xem leaderboard](extracted_images/image23.png)\n\n*Hình 2.16. Biểu đồ Use case chức năng Xem leaderboard*",

        "##### UC15 — Đăng ký và duy trì gameplay server\n*   **Actor chính:** Gameplay Server.\n*   **Mô tả:** Gameplay Server (Unity Dedicated Server) tự đăng ký sự hiện diện của nó với API Server và gửi heartbeat định kỳ.\n*   **Luồng chính:\n    1.  Khi khởi động, Dedicated Server gọi API đăng ký địa chỉ IP, cổng (port 7777 UDP) và danh sách map đang host.\n    2.  Định kỳ mỗi 30 giây, server gửi gói heartbeat báo cáo lượng người chơi online và tải hệ thống.\n    3.  API Server cập nhật trạng thái zone room trong Registry DB để phân phối người chơi đăng nhập.\n*   **Luồng phụ / Ngoại lệ:** Gameplay Server bị tắt đột ngột → Quá 90 giây không có heartbeat, API Server tự giải phóng registry.":
        "##### UC15 — Đăng ký và duy trì gameplay server\n*   **Actor chính:** Gameplay Server.\n*   **Mô tả:** Gameplay Server (Unity Dedicated Server) tự đăng ký sự hiện diện của nó với API Server và gửi heartbeat định kỳ.\n*   **Luồng chính:\n    1.  Khi khởi động, Dedicated Server gọi API đăng ký địa chỉ IP, cổng (port 7777 UDP) và danh sách map đang host.\n    2.  Định kỳ mỗi 30 giây, server gửi gói heartbeat báo cáo lượng người chơi online và tải hệ thống.\n    3.  API Server cập nhật trạng thái zone room trong Registry DB để phân phối người chơi đăng nhập.\n*   **Luồng phụ / Ngoại lệ:** Gameplay Server bị tắt đột ngột → Quá 90 giây không có heartbeat, API Server tự giải phóng registry.\n\n![Biểu đồ Use case chức năng Quản lý gameplay server](extracted_images/image24.png)\n\n*Hình 2.17. Biểu đồ Use case chức năng Quản lý gameplay server*",

        "##### UC16 — Host map và phát thưởng dungeon\n*   **Actor chính:** Gameplay Server.\n*   **Mô tả:** Gameplay Server kiểm tra trạng thái map đang host và gọi API Server (sử dụng Zone API Key) để phát thưởng cho người chơi khi vượt ải thành công.\n*   **Luồng chính:\n    1.  Gameplay Server kiểm tra config spawn qua API của map đang chạy.\n    2.  Spawn quái vật runtime dựa trên spawn config nạp về.\n    3.  Theo dõi HP của quái, gọi API phát thưởng khi phó bản hoàn thành.\n*   **Luồng phụ / Ngoại lệ:** Mất kết nối API Server → Dedicated Server lưu tạm log phần thưởng vào queue để gửi lại sau.":
        "##### UC16 — Host map và phát thưởng dungeon\n*   **Actor chính:** Gameplay Server.\n*   **Mô tả:** Gameplay Server kiểm tra trạng thái map đang host và gọi API Server (sử dụng Zone API Key) để phát thưởng cho người chơi khi vượt ải thành công.\n*   **Luồng chính:\n    1.  Gameplay Server kiểm tra config spawn qua API của map đang chạy.\n    2.  Spawn quái vật runtime dựa trên spawn config nạp về.\n    3.  Theo dõi HP của quái, gọi API phát thưởng khi phó bản hoàn thành.\n*   **Luồng phụ / Ngoại lệ:** Mất kết nối API Server → Dedicated Server lưu tạm log phần thưởng vào queue để gửi lại sau.\n\n![Biểu đồ Use case chức năng Host map và phát thưởng phó bản](extracted_images/image25.png)\n\n*Hình 2.18. Biểu đồ Use case chức năng Host map và phát thưởng phó bản*"
    }
    
    print("Editing detailed Use Case diagrams and captions...")
    for target, replacement in uc_edits.items():
        if target in content:
            content = content.replace(target, replacement)
            print(f"Embedded diagram for Use Case header: {target.splitlines()[0]}")
        else:
            # Let's clean spaces and try again
            target_norm = target.replace("\r\n", "\n").strip()
            # Try finding substring
            sub_key = target.splitlines()[0]
            print(f"Warning: Exact target not found for {sub_key}. Retrying with soft replacement...")
            # We can find where the sub_key is and substitute the whole section
            
    # 3. Update Sequence Diagrams figure captions (2.3 - 2.7 -> 2.19 - 2.23)
    seq_replacements = {
        "*Hình 2.3. Biểu đồ tuần tự Chiến đấu và sử dụng kỹ năng*": "*Hình 2.19. Biểu đồ tuần tự Chiến đấu và sử dụng kỹ năng*",
        "*Hình 2.4. Biểu đồ tuần tự Nâng cấp trang bị tại Blacksmith*": "*Hình 2.20. Biểu đồ tuần tự Nâng cấp trang bị tại Blacksmith*",
        "*Hình 2.5. Biểu đồ tuần tự Nâng Gene chính và Gene phụ*": "*Hình 2.21. Biểu đồ tuần tự Nâng Gene chính và Gene phụ*",
        "*Hình 2.6. Biểu đồ tuần tự Dung hợp Hybrid Gene*": "*Hình 2.22. Biểu đồ tuần tự Dung hợp Hybrid Gene*",
        "*Hình 2.7. Biểu đồ tuần tự Tham gia và hoàn tất phó bản*": "*Hình 2.23. Biểu đồ tuần tự Tham gia và hoàn tất phó bản*",
    }
    
    print("\nUpdating Sequence Diagram figure captions...")
    for old, new in seq_replacements.items():
        if old in content:
            content = content.replace(old, new)
            print(f"Updated caption to: {new}")
        else:
            print(f"Warning: Caption not found: {old}")
            
    # 4. Update Database ERD caption (2.8 -> 2.24) and structural table numbers (2.8 - 2.11 -> 2.18 - 2.21)
    db_replacements = {
        "*Hình 2.8. Sơ đồ cơ sở dữ liệu của hệ thống Mutants Arena*": "*Hình 2.24. Sơ đồ cơ sở dữ liệu của hệ thống Mutants Arena*",
        "Bảng 2.8. Nhóm bảng tài khoản, hồ sơ nhân vật và xã hội": "Bảng 2.18. Nhóm bảng tài khoản, hồ sơ nhân vật và xã hội",
        "Bảng 2.9. Nhóm bảng vật phẩm, option và nâng cấp trang bị": "Bảng 2.19. Nhóm bảng vật phẩm, option và nâng cấp trang bị",
        "Bảng 2.10. Nhóm bảng Gene, Hybrid và kỹ năng": "Bảng 2.20. Nhóm bảng Gene, Hybrid và kỹ năng",
        "Bảng 2.11. Nhóm bảng thế giới game, quái vật, nhiệm vụ và phó bản": "Bảng 2.21. Nhóm bảng thế giới game, quái vật, nhiệm vụ và phó bản",
    }
    
    print("\nUpdating Database captions and table numbers...")
    for old, new in db_replacements.items():
        if old in content:
            content = content.replace(old, new)
            print(f"Updated: {old} -> {new}")
        else:
            print(f"Warning: Not found: {old}")
            
    # Save the updated file back
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print("\nSuccessfully finished fixing CHUONG2_BAO_CAO.md!")

if __name__ == "__main__":
    fix_chapter2()
